### ISSUE TITLE
BaseMaster LOGO

### ISSUE THREAD

**Issue by harunbadilli** [tplloi/basemaster#2]
I have designed a new logo for your application. I brought a new perspective to your logo. I'm giving you a gift. Choose what you want and let me know.
![1](https://user-images.githubusercontent.com/34319922/40547300-39317668-603a-11e8-8563-8f66575a7e15.png)
![2](https://user-images.githubusercontent.com/34319922/40547301-395df882-603a-11e8-9aa6-e659867b09c3.png)
![3](https://user-images.githubusercontent.com/34319922/40547302-398c2f90-603a-11e8-8eea-6d4d3afa7f35.png)
![4](https://user-images.githubusercontent.com/34319922/40547303-39d54ebe-603a-11e8-83dd-2294dd9b5a31.png)

**Comment by tplloi** [comment]
Hi @harunbadilli .
The first icon with blue color looks like great for this library.
If you give me an icon with 512x512px, Iwill change it in the next update.
Thank you.
